import Link from "next/link";
import "../globals.css";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="max-w-5xl mx-auto py-20 " >
        <header className="flex items-center justify-between">
        <Link href="/" className="bg-gradient-to-r from-orange-400 via-red-500 to-purple-600 bg-clip-text text-transparent text-lg font-bold">Sanwal</Link>
        </header>
        <main className="py-20">{children}</main>
        </body>
    </html>
  );
}
